# Builds assets/icons.svg -- one sprite holding every option icon as a <symbol>.
#
#   .\tools\build-icons.ps1
#   .\tools\build-icons.ps1 -Source ..\new-icons -Out assets\icons.svg
#
# Why a sprite rather than <img src="10a.svg">: the drawings are monochrome and
# use stroke="currentColor", so they take their colour from the CSS of the card
# they sit in. An <img> is an isolated document and inherits nothing, which
# would render every icon black and throw away the whole colour system. A
# same-document <use href="#icon-10a"> inherits colour normally.
#
# The sprite is fetched once and injected into the page, so the fifty icons of
# a full item set cost one request instead of fifty.
#
# The source files carry a provenance manifest from the tool that drew them,
# which is about 90% of each file (8,627 bytes in, 891 bytes of drawing). It is
# stripped here: it is of no use to a browser and this runs on school wifi.
#
# NOTE: keep this file ASCII-only (PowerShell 5.1 reads .ps1 as ANSI).
# -Prefix and -PadDigits apply the same id mapping as import-content.ps1, so a
# drawing ends up under the option id that references it: 1a.svg -> icon-Q01a.
# Without them the file stem is used as-is.
param(
  [string]$Source = "vejkend-frontend-24\ikony",
  [string]$Out    = "assets\icons.svg",
  [string]$Prefix = "",
  [int]$PadDigits = 0
)

$root = Split-Path $PSScriptRoot -Parent
$sourceDir = Join-Path $root $Source
$outFile   = Join-Path $root $Out

if (-not (Test-Path $sourceDir)) { throw "No icon source directory at $sourceDir" }
$files = Get-ChildItem $sourceDir -Filter *.svg | Sort-Object Name
if (-not $files) { throw "No .svg files in $sourceDir" }

$utf8 = New-Object System.Text.UTF8Encoding($false)
$symbols = @()
$totalIn = 0
$totalOut = 0

foreach ($file in $files) {
  $raw = [System.IO.File]::ReadAllText($file.FullName, $utf8)
  $totalIn += $raw.Length

  # Drop the provenance manifest and any XML declaration or comments.
  $svg = [regex]::Replace($raw, '<metadata>.*?</metadata>', '', 'Singleline')
  $svg = [regex]::Replace($svg, '<\?xml.*?\?>', '', 'Singleline')
  $svg = [regex]::Replace($svg, '<!--.*?-->', '', 'Singleline')

  # Pull the viewBox and the drawing out of the <svg> wrapper.
  $viewBox = [regex]::Match($svg, 'viewBox="([^"]+)"').Groups[1].Value
  if (-not $viewBox) { throw "$($file.Name): no viewBox, refusing to guess one" }
  $inner = [regex]::Match($svg, '<svg[^>]*>(.*)</svg>', 'Singleline').Groups[1].Value.Trim()
  if (-not $inner) { throw "$($file.Name): could not find the drawing inside <svg>" }

  $stem = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
  if ($Prefix -or $PadDigits -gt 0) {
    if ($stem -match '^(\d+)(.*)$') {
      $stem = $Prefix + ([int]$Matches[1]).ToString().PadLeft($PadDigits, '0') + $Matches[2]
    } else {
      Write-Host ("  note: '{0}' does not start with a number; left unmapped" -f $stem) -ForegroundColor DarkGray
    }
  }
  $id = "icon-" + $stem
  $symbol = '  <symbol id="' + $id + '" viewBox="' + $viewBox + '">' + "`n    " + $inner + "`n  </symbol>"
  $symbols += $symbol
  $totalOut += $symbol.Length
  Write-Host ("  {0,-12} -> {1,-16} {2,6:N0} -> {3,5:N0} bytes" -f $file.Name, $id, $raw.Length, $symbol.Length)
}

# A ring with nothing in it, for options whose drawing has not been made yet.
# Same geometry as the real icons, so a half-illustrated item set still looks
# deliberate instead of broken.
$placeholder = @'
  <symbol id="icon-placeholder" viewBox="0 0 240 240">
    <g fill="none" stroke="currentColor" stroke-width="5.5"><circle cx="120" cy="120" r="104" fill="currentColor" opacity=".05" stroke="none"/><circle cx="120" cy="120" r="104" opacity=".35" stroke-dasharray="10 12"/></g>
  </symbol>
'@

$header = @'
<!-- Generated by tools/build-icons.ps1 -- do not edit by hand.
     Source drawings live in frontend_0917/ikony/. Rebuild after adding icons. -->
<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" style="display:none">
'@

$content = $header + ($symbols -join "`n") + "`n" + $placeholder + "`n</svg>`n"

$outDir = Split-Path $outFile -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
[System.IO.File]::WriteAllText($outFile, $content, $utf8)

Write-Host ""
Write-Host ("Wrote {0} symbols plus a placeholder to {1}" -f $files.Count, $Out)
Write-Host ("Sources {0:N0} bytes -> sprite {1:N0} bytes ({2:P0} smaller)" -f $totalIn, $content.Length, (1 - $content.Length/$totalIn))
